[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/marketplace"
  to = "/marketplace.html"
  status = 200

[[redirects]]
  from = "/explore"
  to = "/explore.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
